In [1]:
# Project Statement

The Film Junky Union, a new edgy community for classic movie enthusiasts, is developing a system for filtering and categorizing movie reviews. The goal is to train a model to automatically detect negative reviews. You'll be using a dataset of IMBD movie reviews with polarity labelling to build a model for classifying positive and negative reviews. It will need to have an F1 score of at least 0.85.

## Initialization

In [2]:
import math
import re

import numpy as np
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import sklearn.metrics as metrics

from tqdm.auto import tqdm
from sklearn.dummy import DummyClassifier

import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

from nltk.corpus import stopwords
import spacy

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from lightgbm import LGBMClassifier

import torch
import transformers

In [3]:

%matplotlib inline
%config InlineBackend.figure_format = 'png'
# the next line provides graphs of better quality on HiDPI screens
%config InlineBackend.figure_format = 'retina'

plt.style.use('seaborn-v0_8-darkgrid')

In [4]:
# this is to use progress_apply, read more at https://pypi.org/project/tqdm/#pandas-integration
tqdm.pandas()

## Load Data

In [5]:
df_reviews = pd.read_csv('datasets/imdb_reviews.tsv', sep='\t', dtype={'votes': 'Int64'})

In [6]:
display(df_reviews.shape)
display(df_reviews.info())
display(df_reviews)

(47331, 17)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47331 entries, 0 to 47330
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   tconst           47331 non-null  object
 1   title_type       47331 non-null  object
 2   primary_title    47331 non-null  object
 3   original_title   47331 non-null  object
 4   start_year       47331 non-null  int64
 5   end_year         47331 non-null  object
 6   runtime_minutes  47331 non-null  object
 7   is_adult         47331 non-null  int64
 8   genres           47331 non-null  object
 9   average_rating   47329 non-null  float64
 10  votes            47329 non-null  Int64
 11  review           47331 non-null  object
 12  rating           47331 non-null  int64
 13  sp               47331 non-null  object
 14  pos              47331 non-null  int64
 15  ds_part          47331 non-null  object
 16  idx              47331 non-null  int64
dtypes: Int64(1), float64(1), int64(5), object(10)
memory usage: 6.2+ MB

None

,tconst,title_type,primary_title,original_title,start_year,end_year,runtime_minutes,is_adult,genres,average_rating,votes,review,rating,sp,pos,ds_part,idx
0,tt0068152,movie,$,$,1971,\N,121,0,"Comedy,Crime,Drama",6.3,2218,The pakage implies that Warren Beatty and Gold...,1,neg,0,train,8335
1,tt0068152,movie,$,$,1971,\N,121,0,"Comedy,Crime,Drama",6.3,2218,How the hell did they get this made?! Presenti...,1,neg,0,train,8336
2,tt0313150,short,'15','15',2002,\N,25,0,"Comedy,Drama,Short",6.3,184,There is no real story the film seems more lik...,3,neg,0,test,2489
3,tt0313150,short,'15','15',2002,\N,25,0,"Comedy,Drama,Short",6.3,184,Um .... a serious film about troubled teens in...,7,pos,1,test,9280
4,tt0313150,short,'15','15',2002,\N,25,0,"Comedy,Drama,Short",6.3,184,I'm totally agree with GarryJohal from Singapo...,9,pos,1,test,9281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47326,tt0068398,tvEpisode,Étude in Black,Étude in Black,1972,\N,97,0,"Crime,Drama,Mystery",7.7,2254,This is another of my favorite Columbos. It sp...,10,pos,1,test,6038
47327,tt0223503,tvMovie,Îhatôbu gensô: KENjI no haru,Îhatôbu gensô: KENjI no haru,1996,\N,55,0,"Animation,Biography,Drama",7.3,278,Talk about being boring! I got this expecting ...,4,neg,0,test,989
47328,tt0223503,tvMovie,Îhatôbu gensô: KENjI no haru,Îhatôbu gensô: KENjI no haru,1996,\N,55,0,"Animation,Biography,Drama",7.3,278,"I never thought I'd say this about a biopic, b...",8,pos,1,test,4163
47329,tt0223503,tvMovie,Îhatôbu gensô: KENjI no haru,Îhatôbu gensô: KENjI no haru,1996,\N,55,0,"Animation,Biography,Drama",7.3,278,Spirit and Chaos is an artistic biopic of Miya...,9,pos,1,test,4164
47330,tt0223503,tvMovie,Îhatôbu gensô: KENjI no haru,Îhatôbu gensô: KENjI no haru,1996,\N,55,0,"Animation,Biography,Drama",7.3,278,I'll make this brief. This was a joy to watch....,10,pos,1,test,4165

In [7]:
# Checking for dupes
print(df_reviews.duplicated().sum())

0

In [8]:
# Checking for nulls.
display(df_reviews.isnull().sum())
df_reviews[df_reviews.isnull().any(axis=1)]

tconst             0
title_type         0
primary_title      0
original_title     0
start_year         0
end_year           0
runtime_minutes    0
is_adult           0
genres             0
average_rating     2
votes              2
review             0
rating             0
sp                 0
pos                0
ds_part            0
idx                0
dtype: int64

,tconst,title_type,primary_title,original_title,start_year,end_year,runtime_minutes,is_adult,genres,average_rating,votes,review,rating,sp,pos,ds_part,idx
22280,tt0192317,movie,Mila Ass Painting,Mila Ass Painting,1998,\N,\N,0,\N,NaN,<NA>,"This is a truly great film, with excellent dir...",9,pos,1,test,3231
22281,tt0192317,movie,Mila Ass Painting,Mila Ass Painting,1998,\N,\N,0,\N,NaN,<NA>,"A film is beyond all expectations, an excellen...",10,pos,1,test,3232

In [9]:
# Dropping the two rows with null values. Since there are only 2 rows out of 47331, this is insiginificant.
df_reviews = df_reviews.dropna(subset=['average_rating'])
display(df_reviews.isnull().sum())

tconst             0
title_type         0
primary_title      0
original_title     0
start_year         0
end_year           0
runtime_minutes    0
is_adult           0
genres             0
average_rating     0
votes              0
review             0
rating             0
sp                 0
pos                0
ds_part            0
idx                0
dtype: int64

## EDA

Let's check the number of movies and reviews over years.

In [10]:
fig, axs = plt.subplots(2, 1, figsize=(16, 8))

ax = axs[0]

dft1 = df_reviews[['tconst', 'start_year']].drop_duplicates() \
    ['start_year'].value_counts().sort_index()
dft1 = dft1.reindex(index=np.arange(dft1.index.min(), max(dft1.index.max(), 2021))).fillna(0)
dft1.plot(kind='bar', ax=ax)
ax.set_title('Number of Movies Over Years')

ax = axs[1]

dft2 = df_reviews.groupby(['start_year', 'pos'])['pos'].count().unstack()
dft2 = dft2.reindex(index=np.arange(dft2.index.min(), max(dft2.index.max(), 2021))).fillna(0)

dft2.plot(kind='bar', stacked=True, label='#reviews (neg, pos)', ax=ax)

dft2 = df_reviews['start_year'].value_counts().sort_index()
dft2 = dft2.reindex(index=np.arange(dft2.index.min(), max(dft2.index.max(), 2021))).fillna(0)
dft3 = (dft2/dft1).fillna(0)
axt = ax.twinx()
dft3.reset_index(drop=True).rolling(5).mean().plot(color='orange', label='reviews per movie (avg over 5 years)', ax=axt)

lines, labels = axt.get_legend_handles_labels()
ax.legend(lines, labels, loc='upper left')

ax.set_title('Number of Reviews Over Years')

fig.tight_layout()

Let's check the distribution of number of reviews per movie with the exact counting and KDE (just to learn how it may differ from the exact counting)

In [11]:
fig, axs = plt.subplots(1, 2, figsize=(16, 5))

ax = axs[0]
dft = df_reviews.groupby('tconst')['review'].count() \
    .value_counts() \
    .sort_index()
dft.plot.bar(ax=ax)
ax.set_title('Bar Plot of #Reviews Per Movie')

ax = axs[1]
dft = df_reviews.groupby('tconst')['review'].count()
sns.kdeplot(dft, ax=ax)
ax.set_title('KDE Plot of #Reviews Per Movie')

fig.tight_layout()

It looks like there a natural break down of one or two reviews per average movie and declining overall. This is true until you hit 30. This means most movies fall under the normal distribution but there is a segment of popular movies where everyone wants to review them. The reviews or at least the count of reviews are probably capped at 30.

In [12]:
df_reviews['pos'].value_counts()

pos
0    23715
1    23614
Name: count, dtype: int64

In [13]:
fig, axs = plt.subplots(1, 2, figsize=(12, 4))

ax = axs[0]
dft = df_reviews.query('ds_part == "train"')['rating'].value_counts().sort_index()
dft = dft.reindex(index=np.arange(min(dft.index.min(), 1), max(dft.index.max(), 11))).fillna(0)
dft.plot.bar(ax=ax)
ax.set_ylim([0, 5000])
ax.set_title('The train set: distribution of ratings')

ax = axs[1]
dft = df_reviews.query('ds_part == "test"')['rating'].value_counts().sort_index()
dft = dft.reindex(index=np.arange(min(dft.index.min(), 1), max(dft.index.max(), 11))).fillna(0)
dft.plot.bar(ax=ax)
ax.set_ylim([0, 5000])
ax.set_title('The test set: distribution of ratings')

fig.tight_layout()

In [14]:
print(df_reviews['rating'].value_counts().sort_index())

rating
1     9589
2     4339
3     4709
4     5078
7     4593
8     5576
9     4342
10    9103
Name: count, dtype: int64

There appears to be an even distribution through the training and test set with a balance between the positive and negative reviews. There are no 5 or 6 ratings. I assume that this is because they were removed or excluded to reduce ambiguity for our purposes.

Distribution of negative and positive reviews over the years for two parts of the dataset

In [15]:
fig, axs = plt.subplots(2, 2, figsize=(16, 8), gridspec_kw=dict(width_ratios=(2, 1), height_ratios=(1, 1)))

ax = axs[0][0]

dft = df_reviews.query('ds_part == "train"').groupby(['start_year', 'pos'])['pos'].count().unstack()
dft.index = dft.index.astype('int')
dft = dft.reindex(index=np.arange(dft.index.min(), max(dft.index.max(), 2020))).fillna(0)
dft.plot(kind='bar', stacked=True, ax=ax)
ax.set_title('The train set: number of reviews of different polarities per year')

ax = axs[0][1]

dft = df_reviews.query('ds_part == "train"').groupby(['tconst', 'pos'])['pos'].count().unstack()
sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)
ax.legend()
ax.set_title('The train set: distribution of different polarities per movie')

ax = axs[1][0]

dft = df_reviews.query('ds_part == "test"').groupby(['start_year', 'pos'])['pos'].count().unstack()
dft.index = dft.index.astype('int')
dft = dft.reindex(index=np.arange(dft.index.min(), max(dft.index.max(), 2020))).fillna(0)
dft.plot(kind='bar', stacked=True, ax=ax)
ax.set_title('The test set: number of reviews of different polarities per year')

ax = axs[1][1]

dft = df_reviews.query('ds_part == "test"').groupby(['tconst', 'pos'])['pos'].count().unstack()
sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)
ax.legend()
ax.set_title('The test set: distribution of different polarities per movie')

fig.tight_layout()

C:\Users\mytho\AppData\Local\Temp\ipykernel_27948\2564148758.py:14: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
C:\Users\mytho\AppData\Local\Temp\ipykernel_27948\2564148758.py:15: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)
C:\Users\mytho\AppData\Local\Temp\ipykernel_27948\2564148758.py:30: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[0], color='blue', label='negative', kernel='epa', ax=ax)
C:\Users\mytho\AppData\Local\Temp\ipykernel_27948\2564148758.py:31: UserWarning:

Support for alternate kernels has been removed; using Gaussian kernel.
This will become an error in seaborn v0.14.0; please update your code.

  sns.kdeplot(dft[1], color='green', label='positive', kernel='epa', ax=ax)

This shows a higher of distribution of negative reviews on movies with 1 and 2 reviews. While positive movies have a high 1 and 2 reviews, they aren't as high as the negative reviews and have a much higher review count at 30 and a spread across all reviews. This is in line with our intuitions. Popular movies have probably hit the cap at 30 reviews, bad movies have one or two negative reviews which turn other people off from watching them. As time progress there are more and more movie reviews. There does seem to be a dip in the early 60s. I am not sure what accounts for this and will probably need additional investigation.

## Evaluation Procedure

Composing an evaluation routine which can be used for all models in this project

In [16]:
# import sklearn.metrics as metrics (moved to the top).

def evaluate_model(model, train_features, train_target, test_features, test_target):
    
    eval_stats = {}
    
    fig, axs = plt.subplots(1, 3, figsize=(20, 6)) 
    
    for type, features, target in (('train', train_features, train_target), ('test', test_features, test_target)):
        
        eval_stats[type] = {}
    
        pred_target = model.predict(features)
        pred_proba = model.predict_proba(features)[:, 1]
        
        # F1
        f1_thresholds = np.arange(0, 1.01, 0.05)
        f1_scores = [metrics.f1_score(target, pred_proba>=threshold) for threshold in f1_thresholds]
        
        # ROC
        fpr, tpr, roc_thresholds = metrics.roc_curve(target, pred_proba)
        roc_auc = metrics.roc_auc_score(target, pred_proba)    
        eval_stats[type]['ROC AUC'] = roc_auc

        # PRC
        precision, recall, pr_thresholds = metrics.precision_recall_curve(target, pred_proba)
        aps = metrics.average_precision_score(target, pred_proba)
        eval_stats[type]['APS'] = aps
        
        if type == 'train':
            color = 'blue'
        else:
            color = 'green'

        # F1 Score
        ax = axs[0]
        max_f1_score_idx = np.argmax(f1_scores)
        ax.plot(f1_thresholds, f1_scores, color=color, label=f'{type}, max={f1_scores[max_f1_score_idx]:.2f} @ {f1_thresholds[max_f1_score_idx]:.2f}')
        # setting crosses for some thresholds
        for threshold in (0.2, 0.4, 0.5, 0.6, 0.8):
            closest_value_idx = np.argmin(np.abs(f1_thresholds-threshold))
            marker_color = 'orange' if threshold != 0.5 else 'red'
            ax.plot(f1_thresholds[closest_value_idx], f1_scores[closest_value_idx], color=marker_color, marker='X', markersize=7)
        ax.set_xlim([-0.02, 1.02])    
        ax.set_ylim([-0.02, 1.02])
        ax.set_xlabel('threshold')
        ax.set_ylabel('F1')
        ax.legend(loc='lower center')
        ax.set_title(f'F1 Score') 

        # ROC
        ax = axs[1]    
        ax.plot(fpr, tpr, color=color, label=f'{type}, ROC AUC={roc_auc:.2f}')
        # setting crosses for some thresholds
        for threshold in (0.2, 0.4, 0.5, 0.6, 0.8):
            closest_value_idx = np.argmin(np.abs(roc_thresholds-threshold))
            marker_color = 'orange' if threshold != 0.5 else 'red'            
            ax.plot(fpr[closest_value_idx], tpr[closest_value_idx], color=marker_color, marker='X', markersize=7)
        ax.plot([0, 1], [0, 1], color='grey', linestyle='--')
        ax.set_xlim([-0.02, 1.02])    
        ax.set_ylim([-0.02, 1.02])
        ax.set_xlabel('FPR')
        ax.set_ylabel('TPR')
        ax.legend(loc='lower center')        
        ax.set_title(f'ROC Curve')
        
        # PRC
        ax = axs[2]
        ax.plot(recall, precision, color=color, label=f'{type}, AP={aps:.2f}')
        # setting crosses for some thresholds
        for threshold in (0.2, 0.4, 0.5, 0.6, 0.8):
            closest_value_idx = np.argmin(np.abs(pr_thresholds-threshold))
            marker_color = 'orange' if threshold != 0.5 else 'red'
            ax.plot(recall[closest_value_idx], precision[closest_value_idx], color=marker_color, marker='X', markersize=7)
        ax.set_xlim([-0.02, 1.02])    
        ax.set_ylim([-0.02, 1.02])
        ax.set_xlabel('recall')
        ax.set_ylabel('precision')
        ax.legend(loc='lower center')
        ax.set_title(f'PRC')        

        eval_stats[type]['Accuracy'] = metrics.accuracy_score(target, pred_target)
        eval_stats[type]['F1'] = metrics.f1_score(target, pred_target)
    
    df_eval_stats = pd.DataFrame(eval_stats)
    df_eval_stats = df_eval_stats.round(2)
    df_eval_stats = df_eval_stats.reindex(index=('Accuracy', 'F1', 'APS', 'ROC AUC'))
    
    print(df_eval_stats)
    
    return

## Normalization

We assume all models below accepts texts in lowercase and without any digits, punctuations marks etc.

In [17]:
# Function for noramlize_text.
def normalize_text(text):
    if pd.isnull(text):
        return""
    # Convert to lowercase
    text = text.lower()
    # Remove punctuation and digits
    text = re.sub(r'[^\w\s]', '', text)      # Removes punctuation
    text = re.sub(r'\d+', '', text)          # Removes digits
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df_reviews['review_norm'] = df_reviews['review'].apply(normalize_text)# <put your code here>
print(df_reviews)

          tconst title_type                 primary_title  \
0      tt0068152      movie                             $
1      tt0068152      movie                             $
2      tt0313150      short                          '15'
3      tt0313150      short                          '15'
4      tt0313150      short                          '15'
...          ...        ...                           ...
47326  tt0068398  tvEpisode                Étude in Black
47327  tt0223503    tvMovie  Îhatôbu gensô: KENjI no haru
47328  tt0223503    tvMovie  Îhatôbu gensô: KENjI no haru
47329  tt0223503    tvMovie  Îhatôbu gensô: KENjI no haru
47330  tt0223503    tvMovie  Îhatôbu gensô: KENjI no haru

                     original_title  start_year end_year runtime_minutes  \
0                                 $        1971       \N             121
1                                 $        1971       \N             121
2                              '15'        2002       \N              25
3                              '15'        2002       \N              25
4                              '15'        2002       \N              25
...                             ...         ...      ...             ...
47326                Étude in Black        1972       \N              97
47327  Îhatôbu gensô: KENjI no haru        1996       \N              55
47328  Îhatôbu gensô: KENjI no haru        1996       \N              55
47329  Îhatôbu gensô: KENjI no haru        1996       \N              55
47330  Îhatôbu gensô: KENjI no haru        1996       \N              55

       is_adult                     genres  average_rating  votes  \
0             0         Comedy,Crime,Drama             6.3   2218
1             0         Comedy,Crime,Drama             6.3   2218
2             0         Comedy,Drama,Short             6.3    184
3             0         Comedy,Drama,Short             6.3    184
4             0         Comedy,Drama,Short             6.3    184
...         ...                        ...             ...    ...
47326         0        Crime,Drama,Mystery             7.7   2254
47327         0  Animation,Biography,Drama             7.3    278
47328         0  Animation,Biography,Drama             7.3    278
47329         0  Animation,Biography,Drama             7.3    278
47330         0  Animation,Biography,Drama             7.3    278

                                                  review  rating   sp  pos  \
0      The pakage implies that Warren Beatty and Gold...       1  neg    0
1      How the hell did they get this made?! Presenti...       1  neg    0
2      There is no real story the film seems more lik...       3  neg    0
3      Um .... a serious film about troubled teens in...       7  pos    1
4      I'm totally agree with GarryJohal from Singapo...       9  pos    1
...                                                  ...     ...  ...  ...
47326  This is another of my favorite Columbos. It sp...      10  pos    1
47327  Talk about being boring! I got this expecting ...       4  neg    0
47328  I never thought I'd say this about a biopic, b...       8  pos    1
47329  Spirit and Chaos is an artistic biopic of Miya...       9  pos    1
47330  I'll make this brief. This was a joy to watch....      10  pos    1

      ds_part   idx                                        review_norm
0       train  8335  the pakage implies that warren beatty and gold...
1       train  8336  how the hell did they get this made presenting...
2        test  2489  there is no real story the film seems more lik...
3        test  9280  um a serious film about troubled teens in sing...
4        test  9281  im totally agree with garryjohal from singapor...
...       ...   ...                                                ...
47326    test  6038  this is another of my favorite columbos it spo...
47327    test   989  talk about being boring i got this expecting a...
47328    test  4163  i never thought id say this about a biopic but...
47329    test  4164  spirit and chaos is an artistic biopic of miya...
47330    test  4165  ill make this brief this was a joy to watch it...

[47329 rows x 18 columns]

## Train / Test Split

Luckily, the whole dataset is already divided into train/test one parts. The corresponding flag is 'ds_part'.

In [18]:
df_reviews_train = df_reviews.query('ds_part == "train"').copy()
df_reviews_test = df_reviews.query('ds_part == "test"').copy()


train_target = df_reviews_train['pos']
train_features = df_reviews_train.drop(columns=['pos'])

test_target = df_reviews_test['pos']
test_features = df_reviews_test.drop(columns=['pos'])


print(df_reviews_train.shape)
print(df_reviews_test.shape)

(23796, 18)
(23533, 18)

## Working with models

### Model 0 - Constant

In [19]:
# from sklearn.dummy import DummyClassifier (moved to top)

In [20]:
model_0 = DummyClassifier(strategy="most_frequent")
model_0.fit(train_features, train_target)

DummyClassifier(strategy='most_frequent')

In [21]:
preds_0 = model_0.predict(test_features)

In [22]:
evaluate_model(model_0,train_features, train_target, test_features, test_target)

          train  test
Accuracy    0.5   0.5
F1          0.0   0.0
APS         0.5   0.5
ROC AUC     0.5   0.5

### Model 1 - NLTK, TF-IDF and LR

TF-IDF

In [23]:
# import nltk (moved this section to the top)

# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.linear_model import LogisticRegression

# from nltk.corpus import stopwords

In [24]:
# Download needed resources
nltk.download('punkt')
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

vectorizer = TfidfVectorizer(max_features=5000)
train_features_1 = vectorizer.fit_transform(df_reviews_train['review_norm'])
test_features_1 = vectorizer.transform(df_reviews_test['review_norm'])

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mytho\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mytho\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
model_1 = LogisticRegression()
model_1.fit(train_features_1, train_target)

LogisticRegression()

In [26]:
evaluate_model(model_1, train_features_1, train_target, test_features_1, test_target)

          train  test
Accuracy   0.91  0.88
F1         0.91  0.88
APS        0.97  0.95
ROC AUC    0.97  0.95

### Model 3 - spaCy, TF-IDF and LR

In [27]:
# import spacy (moved to top)

nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

In [28]:
def text_preprocessing_3(text):
    
    doc = nlp(text)
    #tokens = [token.lemma_ for token in doc if not token.is_stop]
    tokens = [token.lemma_ for token in doc]
    tempstring = ' '.join(tokens)
    
    return tempstring

In [29]:
train_features_tfidf_3 = vectorizer.fit_transform(train_features['review_norm'].apply(text_preprocessing_3))
test_features_tfidf_3 = vectorizer.transform(test_features['review_norm'].apply(text_preprocessing_3))

In [30]:
model_3 = LogisticRegression(max_iter=1000)
model_3.fit(train_features_tfidf_3, train_target)

evaluate_model(model_3, train_features_tfidf_3, train_target, test_features_tfidf_3, test_target)

          train  test
Accuracy   0.91  0.88
F1         0.91  0.88
APS        0.97  0.95
ROC AUC    0.97  0.95

### Model 4 - spaCy, TF-IDF and LGBMClassifier

In [31]:
# from lightgbm import LGBMClassifier (moved to the top)
train_features_tfidf_4 = vectorizer.fit_transform(train_features['review_norm'].apply(text_preprocessing_3))
test_features_tfidf_4 = vectorizer.transform(test_features['review_norm'].apply(text_preprocessing_3))

In [32]:
model_4 = LGBMClassifier(n_estimators=200, learning_rate=0.1, random_state=42)
model_4.fit(train_features_tfidf_4, train_target)

[LightGBM] [Info] Number of positive: 11884, number of negative: 11912
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.134413 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 418605
[LightGBM] [Info] Number of data points in the train set: 23796, number of used features: 4994
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499412 -> initscore=-0.002353
[LightGBM] [Info] Start training from score -0.002353

LGBMClassifier(n_estimators=200, random_state=42)

In [33]:
evaluate_model(model_4, train_features_tfidf_4, train_target, test_features_tfidf_4, test_target)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

          train  test
Accuracy   0.96  0.87
F1         0.96  0.87
APS        0.99  0.94
ROC AUC    0.99  0.94

###  Model 9 - BERT

In [34]:
# import torch (moved to the top)
# import transformers

In [35]:
#tokenizer = transformers.BertTokenizer.from_pretrained('bert-base-uncased')
#config = transformers.BertConfig.from_pretrained('bert-base-uncased')
#model = transformers.BertModel.from_pretrained('bert-base-uncased')

In [36]:

'''def BERT_text_to_embeddings(texts, max_length=512, batch_size=100, force_device=None, disable_progress_bar=False):
    
    ids_list = []
    attention_mask_list = []

    # text to padded ids of tokens along with their attention masks
    for text in texts:
    encoded = tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_attention_mask=True,
        return_tensors='pt'
    )
    ids_list.append(encoded['input_ids'].squeeze().tolist())
    attention_mask_list.append(encoded['attention_mask'].squeeze().tolist())
    # <put your code here to create ids_list and attention_mask_list>
    attention_mask_batch = torch.LongTensor(attention_mask_list[batch_size*i:batch_size*(i+1)]).to(device)
    if force_device is not None:
        device = torch.device(force_device)
    else:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        
    model.to(device)
    if not disable_progress_bar:
        print(f'Using the {device} device.')
    
    # gettings embeddings in batches

    embeddings = []

    for i in tqdm(range(math.ceil(len(ids_list)/batch_size)), disable=disable_progress_bar):
            
        ids_batch = torch.LongTensor(ids_list[batch_size*i:batch_size*(i+1)]).to(device)
        # <put your code here to create attention_mask_batch
            
        with torch.no_grad():            
            model.eval()
            batch_embeddings = model(input_ids=ids_batch, attention_mask=attention_mask_batch)   
        embeddings.append(batch_embeddings[0][:,0,:].detach().cpu().numpy())
        
    return np.concatenate(embeddings)'''

"def BERT_text_to_embeddings(texts, max_length=512, batch_size=100, force_device=None, disable_progress_bar=False):\n    \n    ids_list = []\n    attention_mask_list = []\n\n    # text to padded ids of tokens along with their attention masks\n    for text in texts:\n    encoded = tokenizer.encode_plus(\n        text,\n        add_special_tokens=True,\n        max_length=max_length,\n        padding='max_length',\n        truncation=True,\n        return_attention_mask=True,\n        return_tensors='pt'\n    )\n    ids_list.append(encoded['input_ids'].squeeze().tolist())\n    attention_mask_list.append(encoded['attention_mask'].squeeze().tolist())\n    # <put your code here to create ids_list and attention_mask_list>\n    attention_mask_batch = torch.LongTensor(attention_mask_list[batch_size*i:batch_size*(i+1)]).to(device)\n    if force_device is not None:\n        device = torch.device(force_device)\n    else:\n        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n        \n    model.to(device)\n    if not disable_progress_bar:\n        print(f'Using the {device} device.')\n    \n    # gettings embeddings in batches\n\n    embeddings = []\n\n    for i in tqdm(range(math.ceil(len(ids_list)/batch_size)), disable=disable_progress_bar):\n            \n        ids_batch = torch.LongTensor(ids_list[batch_size*i:batch_size*(i+1)]).to(device)\n        # <put your code here to create attention_mask_batch\n            \n        with torch.no_grad():            \n            model.eval()\n            batch_embeddings = model(input_ids=ids_batch, attention_mask=attention_mask_batch)   \n        embeddings.append(batch_embeddings[0][:,0,:].detach().cpu().numpy())\n        \n    return np.concatenate(embeddings)"

In [37]:
# Attention! Running BERT for thousands of texts may take long run on CPU, at least several hours
#train_features_9 = BERT_text_to_embeddings(df_reviews_train['review_norm'])

In [38]:
#test_features_9 = BERT_text_to_embeddings(df_reviews_test['review_norm'])

In [39]:

'''print(df_reviews_train['review_norm'].shape)

print(train_features_9.shape)
print(train_target.shape)

print(test_features_9.shape)
print(test_target.shape)
'''

"print(df_reviews_train['review_norm'].shape)\n\nprint(train_features_9.shape)\nprint(train_target.shape)\n\nprint(test_features_9.shape)\nprint(test_target.shape)\n"

In [40]:
# if you have got the embeddings, it's advisable to save them to have them ready if 
# np.savez_compressed('features_9.npz', train_features_9=train_features_9, test_features_9=test_features_9)

# and load...
# with np.load('features_9.npz') as data:
#     train_features_9 = data['train_features_9']
#     test_features_9 = data['test_features_9']

## My Reviews

In [41]:
# feel free to completely remove these reviews and try your models on your own reviews, those below are just examples

my_reviews = pd.DataFrame([
    "I did not simply like it, not my kind of movie.",
    "Well, I was bored and fell asleep in the middle of the movie.",
    "I was really fascinated with the movie",
    "Even the actors looked really old and disinterested, and they got paid to be in the movie. What a soulless cash grab.",
    "I didn't expect the reboot to be so good! Writers really cared about the source material",
    "The movie had its upsides and downsides, but I feel like overall it's a decent flick. I could see myself going to see it again.",
    "What a rotten attempt at a comedy. Not a single joke lands, everyone acts annoying and loud, even kids won't like this!",
    "Launching on Netflix was a brave move & I really appreciate being able to binge on episode after episode of this exciting intelligent new drama."
], columns=['review'])

my_reviews['review_norm'] = my_reviews['review'].apply(normalize_text)# <put here the same normalization logic as for the main dataset>

my_reviews

,review,review_norm
0,"I did not simply like it, not my kind of movie.",i did not simply like it not my kind of movie
1,"Well, I was bored and fell asleep in the middl...",well i was bored and fell asleep in the middle...
2,I was really fascinated with the movie,i was really fascinated with the movie
3,Even the actors looked really old and disinter...,even the actors looked really old and disinter...
4,I didn't expect the reboot to be so good! Writ...,i didnt expect the reboot to be so good writer...
5,"The movie had its upsides and downsides, but I...",the movie had its upsides and downsides but i ...
6,What a rotten attempt at a comedy. Not a singl...,what a rotten attempt at a comedy not a single...
7,Launching on Netflix was a brave move & I real...,launching on netflix was a brave move i really...

### Model 1

In [42]:
texts = my_reviews['review_norm']

my_reviews_pred_prob = model_1.predict_proba(vectorizer.transform(texts))[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.53:  i did not simply like it not my kind of movie
0.58:  well i was bored and fell asleep in the middle of the movie
0.31:  i was really fascinated with the movie
0.56:  even the actors looked really old and disinterested and they got paid to be in the movie what a soul
0.33:  i didnt expect the reboot to be so good writers really cared about the source material
0.38:  the movie had its upsides and downsides but i feel like overall its a decent flick i could see mysel
0.34:  what a rotten attempt at a comedy not a single joke lands everyone acts annoying and loud even kids
0.77:  launching on netflix was a brave move i really appreciate being able to binge on episode after episo

### Model 3

In [43]:
texts = my_reviews['review_norm']

my_reviews_pred_prob = model_3.predict_proba(vectorizer.transform(texts.apply(lambda x: text_preprocessing_3(x))))[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.17:  i did not simply like it not my kind of movie
0.16:  well i was bored and fell asleep in the middle of the movie
0.66:  i was really fascinated with the movie
0.13:  even the actors looked really old and disinterested and they got paid to be in the movie what a soul
0.15:  i didnt expect the reboot to be so good writers really cared about the source material
0.74:  the movie had its upsides and downsides but i feel like overall its a decent flick i could see mysel
0.04:  what a rotten attempt at a comedy not a single joke lands everyone acts annoying and loud even kids
0.92:  launching on netflix was a brave move i really appreciate being able to binge on episode after episo

### Model 4

In [44]:
texts = my_reviews['review_norm']

# tfidf_vectorizer_4 = tfidf_vectorizer_3
my_reviews_pred_prob = model_4.predict_proba(vectorizer.transform(texts.apply(lambda x: text_preprocessing_3(x))))[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')

0.45:  i did not simply like it not my kind of movie
0.37:  well i was bored and fell asleep in the middle of the movie
0.67:  i was really fascinated with the movie
0.54:  even the actors looked really old and disinterested and they got paid to be in the movie what a soul
0.26:  i didnt expect the reboot to be so good writers really cared about the source material
0.85:  the movie had its upsides and downsides but i feel like overall its a decent flick i could see mysel
0.19:  what a rotten attempt at a comedy not a single joke lands everyone acts annoying and loud even kids
0.90:  launching on netflix was a brave move i really appreciate being able to binge on episode after episo

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

### Model 9

In [45]:
'''texts = my_reviews['review_norm']

my_reviews_features_9 = BERT_text_to_embeddings(texts, disable_progress_bar=True)

my_reviews_pred_prob = model_9.predict_proba(my_reviews_features_9)[:, 1]

for i, review in enumerate(texts.str.slice(0, 100)):
    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')'''

"texts = my_reviews['review_norm']\n\nmy_reviews_features_9 = BERT_text_to_embeddings(texts, disable_progress_bar=True)\n\nmy_reviews_pred_prob = model_9.predict_proba(my_reviews_features_9)[:, 1]\n\nfor i, review in enumerate(texts.str.slice(0, 100)):\n    print(f'{my_reviews_pred_prob[i]:.2f}:  {review}')"

## Conclusions

Based off our results:

- Model 1 is the logistic regression model the values tended to be more neutral and and the system was unable to make up its mind.
- Model 3 tended to be more extreme than the other models.
- Model 4 has strong positive and softer on the negatives.

Based off of this, LR model seems kind of useless for us. Further diving into specific examples:

Model 3:
0.51:  i was really fascinated with the movie
0.13:  even the actors looked really old and disinterested and they got paid to be in the movie what a soul
0.15:  i didnt expect the reboot to be so good writers really cared about the source material

Model 4:
0.68:  i was really fascinated with the movie
0.53:  even the actors looked really old and disinterested and they got paid to be in the movie what a soul
0.23:  i didnt expect the reboot to be so good writers really cared about the source material

Model 3 got the first example wrong and called it a neutral but the model 4 was more confident about the positivity. Both were a little on the softer side than I expected.
For the second example, Model 3 got this right where as model 4 really missed the mark. Both missed the mark for the final example I pulled. They were both predicting a negative score but looks positive to me.

To get a better result I might suggest, using a blend of model 3 and 4. Perhaps using a weighted average of the results based off of further testing.